Repository add-ons/plugin.video.viervijfzes, pull requests merged in 2020-11, with the labels that each got.

#49 Allow to install IPTV Manager from the settings
  resources/settings.xml
Labels: enhancement

#50 Allow to install and run Kodi Logfile Uploader from the settings
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/settings.xml
Labels: enhancement

#47 Allow playing drm protected content
  resources/lib/kodiutils.py
  resources/lib/modules/player.py
  resources/lib/viervijfzes/__init__.py
  resources/lib/viervijfzes/content.py
  tests/__init__.py
  tests/test_api.py
Labels: enhancement

#54 Fix EPG due to parsing issue of the season
  resources/lib/modules/iptvmanager.py
  resources/lib/viervijfzes/epg.py
Labels: bug

#55 Fix clearing local metadata
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/modules/metadata.py
Labels: bug

#59 Fix CI tests
  Makefile
  requirements.txt
  resources/lib/modules/player.py
  resources/lib/viervijfzes/auth.py
  tests/test_api.py
  tests/test_epg.py
Labels: testing

#58 Fix authentication on some older Android devices
  resources/lib/viervijfzes/auth_awsidp.py
Labels: bug

#60 Add support for Python 3.9
  .github/workflows/ci.yml
  resources/lib/viervijfzes/content.py
  tox.ini
Labels: testing
