Repository add-ons/plugin.video.viervijfzes, pull requests merged in 2020-03, with the labels that each got.

#12 Small translation fixes
  resources/language/resource.language.nl_nl/strings.po
Labels: translations

#13 Improve EPG metadata
  resources/lib/modules/menu.py
  resources/lib/modules/tvguide.py
  resources/lib/viervijfzes/epg.py
Labels: enhancement

#7 Small workaround using OMXPlayer
  resources/lib/kodiutils.py
  resources/lib/modules/player.py
Labels: arm, bug, kodi

#11 Various check fixes
  .pylintrc
  Makefile
  resources/lib/addon.py
  resources/lib/modules/catalog.py
  resources/lib/service.py
  resources/lib/viervijfzes/auth.py
  resources/lib/viervijfzes/auth_awsidp.py
  resources/lib/viervijfzes/content.py
  resources/lib/viervijfzes/epg.py
  test/test_routing.py
  tox.ini
Labels: testing

#14 Improve CI tests
  .gitattributes
  .github/workflows/addon-check.yml
  .github/workflows/ci.yml
  Makefile
  README.md
  requirements.txt
  resources/lib/viervijfzes/auth.py
  resources/lib/viervijfzes/auth_awsidp.py
  resources/lib/viervijfzes/content.py
  test/run.py
  test/userdata/addon_settings.json
  test/xbmc.py
Labels: testing
