Repository add-ons/plugin.video.viervijfzes, pull requests merged in 2021-02, with the labels that each got.

#66 Make use of git archive
  Makefile
Labels: testing

#70 Remove dependency on tox
  .gitattributes
  .github/workflows/ci.yml
  Makefile
  requirements.txt
  tox.ini
Labels: testing

#71 Implement My List
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/modules/catalog.py
  resources/lib/modules/menu.py
  resources/lib/modules/player.py
  resources/lib/viervijfzes/auth.py
  resources/lib/viervijfzes/aws/__init__.py
  resources/lib/viervijfzes/aws/cognito_identity.py
  resources/lib/viervijfzes/aws/cognito_idp.py
  resources/lib/viervijfzes/aws/cognito_sync.py
  resources/lib/viervijfzes/content.py
  resources/lib/viervijfzes/search.py
  tests/test_auth.py
  tests/test_mylist.py
Labels: enhancement

#72 Cleanup CI
  .github/workflows/addon-check.yml
  .github/workflows/ci.yml
  requirements.txt
  resources/lib/addon.py
  resources/lib/service.py
  tests/test_service.py
Labels: testing

#73 Fix error when requesting a My List that has not been created yet.
  resources/lib/modules/catalog.py
  resources/lib/viervijfzes/auth.py
  resources/lib/viervijfzes/aws/cognito_sync.py
  tests/test_mylist.py
Labels: bug

#74 Remove background metadata downloading
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/modules/metadata.py
  resources/lib/service.py
  resources/lib/viervijfzes/aws/cognito_sync.py
  resources/lib/viervijfzes/content.py
  resources/settings.xml
  tests/test_routing.py
Labels: enhancement

#75 Fix incomplete descriptions
  resources/lib/kodiutils.py
  resources/lib/modules/catalog.py
  resources/lib/viervijfzes/content.py
Labels: enhancement

#76 Add recommendations and categories, allow to hide unavailable programs
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/addon.py
  resources/lib/kodiutils.py
  resources/lib/modules/catalog.py
  resources/lib/modules/channels.py
  resources/lib/modules/menu.py
  resources/lib/modules/player.py
  resources/lib/modules/tvguide.py
  resources/lib/viervijfzes/content.py
  resources/settings.xml
  tests/test_api.py
  tests/test_routing.py
Labels: enhancement
